


  export const carBrands = [
         
  { name: 'Toyota', country: 'Japan' },
  { name: 'Ford', country: 'USA' },
  { name: 'BMW', country: 'Germany' },
  { name: 'Audi', country: 'Germany' },
  { name: 'Honda', country: 'Japan' },
  { name: 'Chevrolet', country: 'USA' },
  { name: 'Ferrari', country: 'Italy' },
  { name: 'Lamborghini', country: 'Italy' },
  { name: 'Nissan', country: 'Japan' },
  { name: 'Mercedes-Benz', country: 'Germany' }
]
export const AfricanCountrys = [
  { "name": "Algeria", "capital": "Algiers", "isoCode": "DZ" },
  { "name": "Angola", "capital": "Luanda", "isoCode": "AO" },
  { "name": "Benin", "capital": "Porto-Novo", "isoCode": "BJ" },
  { "name": "Botswana", "capital": "Gaborone", "isoCode": "BW" },
  { "name": "Burkina Faso", "capital": "Ouagadougou", "isoCode": "BF" },
  { "name": "Burundi", "capital": "Gitega", "isoCode": "BI" },
  { "name": "Cabo Verde", "capital": "Praia", "isoCode": "CV" },
  { "name": "Cameroon", "capital": "Yaoundé", "isoCode": "CM" },
  { "name": "Central African Republic", "capital": "Bangui", "isoCode": "CF" },
  { "name": "Chad", "capital": "N'Djamena", "isoCode": "TD" },
  { "name": "Comoros", "capital": "Moroni", "isoCode": "KM" },
  { "name": "Congo (Congo-Brazzaville)", "capital": "Brazzaville", "isoCode": "CG" },
  { "name": "Congo (Democratic Republic of the Congo)", "capital": "Kinshasa", "isoCode": "CD" },
  { "name": "Djibouti", "capital": "Djibouti", "isoCode": "DJ" },
  { "name": "Egypt", "capital": "Cairo", "isoCode": "EG" },
  { "name": "Equatorial Guinea", "capital": "Malabo", "isoCode": "GQ" },
  { "name": "Eritrea", "capital": "Asmara", "isoCode": "ER" },
  { "name": "Eswatini", "capital": "Mbabane", "isoCode": "SZ" },
  { "name": "Ethiopia", "capital": "Addis Ababa", "isoCode": "ET" },
  { "name": "Gabon", "capital": "Libreville", "isoCode": "GA" },
  { "name": "Gambia", "capital": "Banjul", "isoCode": "GM" },
  { "name": "Ghana", "capital": "Accra", "isoCode": "GH" },
  { "name": "Guinea", "capital": "Conakry", "isoCode": "GN" },
  { "name": "Guinea-Bissau", "capital": "Bissau", "isoCode": "GW" },
  { "name": "Ivory Coast (Côte d'Ivoire)", "capital": "Yamoussoukro", "isoCode": "CI" },
  { "name": "Kenya", "capital": "Nairobi", "isoCode": "KE" },
  { "name": "Lesotho", "capital": "Maseru", "isoCode": "LS" },
  { "name": "Liberia", "capital": "Monrovia", "isoCode": "LR" },
  { "name": "Libya", "capital": "Tripoli", "isoCode": "LY" },
  { "name": "Madagascar", "capital": "Antananarivo", "isoCode": "MG" },
  { "name": "Malawi", "capital": "Lilongwe", "isoCode": "MW" },
  { "name": "Mali", "capital": "Bamako", "isoCode": "ML" },
  { "name": "Mauritania", "capital": "Nouakchott", "isoCode": "MR" },
  { "name": "Mauritius", "capital": "Port Louis", "isoCode": "MU" },
  { "name": "Morocco", "capital": "Rabat", "isoCode": "MA" },
  { "name": "Mozambique", "capital": "Maputo", "isoCode": "MZ" },
  { "name": "Namibia", "capital": "Windhoek", "isoCode": "NA" },
  { "name": "Niger", "capital": "Niamey", "isoCode": "NE" },
  { "name": "Nigeria", "capital": "Abuja", "isoCode": "NG" },
  { "name": "Rwanda", "capital": "Kigali", "isoCode": "RW" },
  { "name": "São Tomé and Príncipe", "capital": "São Tomé", "isoCode": "ST" },
  { "name": "Senegal", "capital": "Dakar", "isoCode": "SN" },
  { "name": "Seychelles", "capital": "Victoria", "isoCode": "SC" },
  { "name": "Sierra Leone", "capital": "Freetown", "isoCode": "SL" },
  { "name": "Somalia", "capital": "Mogadishu", "isoCode": "SO" },
  { "name": "South Africa", "capital": "Pretoria (administrative)", "isoCode": "ZA" },
  { "name": "South Sudan", "capital": "Juba", "isoCode": "SS" },
  { "name": "Sudan", "capital": "Khartoum", "isoCode": "SD" },
  { "name": "Togo", "capital": "Lomé", "isoCode": "TG" },
  { "name": "Tunisia", "capital": "Tunis", "isoCode": "TN" },
  { "name": "Uganda", "capital": "Kampala", "isoCode": "UG" },
  { "name": "Zambia", "capital": "Lusaka", "isoCode": "ZM" },
  { "name": "Zimbabwe", "capital": "Harare", "isoCode": "ZW" }
]
